name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Dart SDK
        uses: dart-lang/setup-dart@v1

      - name: Test and generate coverage report
        run: |
          dart pub get
          dart format --output none --set-exit-if-changed .
          dart analyze
          dart run coverage:test_with_coverage --function-coverage --branch-coverage

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2

  format-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Format Markdown with markdownlint
        run: |
          npm install -g markdownlint-cli
          markdownlint --disable MD013 MD033 --fix . --ignore CODE_OF_CONDUCT.md --ignore CHANGELOG.md
          git add -A
          git diff --cached --exit-code
