name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Dart SDK
        uses: dart-lang/setup-dart@v1

      - name: Install lcov (Ubuntu)
        run: sudo apt-get update && sudo apt-get install -y lcov

      - name: Test and generate coverage report
        run: |
          make tests_with_coverage_report

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2

  format-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Format Markdown with markdownlint
        run: |
          npm install -g markdownlint-cli
          markdownlint --disable MD013 MD033 --fix . --ignore CODE_OF_CONDUCT.md --ignore CHANGELOG.md
          git add -A
          git diff --cached --exit-code
